# -*- coding: utf-8 -*-
"""LinePlot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hEBXEki21MG81AGEGmrLJwJyqzdibhjR
"""

from google.colab import drive
drive.mount("/content/drive/")

import pandas as pd
import numpy as np
import os

os.listdir("/content/drive/My Drive/ProbStats Project")

deaths = pd.read_csv("/content/drive/My Drive/Probability Project/csse_covid_19_data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv")
cases = pd.read_csv("/content/drive/My Drive/Probability Project/csse_covid_19_data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv")
recovered = pd.read_csv("/content/drive/My Drive/Probability Project/csse_covid_19_data/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv")

cases.columns[4:]

dates = deaths.columns[4:]

dates

recovered.columns[4:]

data = []      
ndeaths = deaths.values[0,4:]
ncases = cases.values[0,4:]
nrecovered = recovered.values[0,4:]
for ix in range(len(dates)):
  data.append([dates[ix],ndeaths[ix],ncases[ix],nrecovered[ix]])

pd.DataFrame(data, columns = ['date','deaths','cases','recovered']).to_csv("myfile.csv",index = False)